 baseURL = "https://jupro2.github.io/"
   locale = "zh-cn"
   title = "Welcome"
   theme = "PaperMod"

   [params]
     env = "production"
     description = "my personal blog"
     author = "Aeolus"
     defaultTheme = "auto"
     ShowReadingTime = true
     ShowShareButtons = true
     ShowPostNavLinks = true
     ShowCodeCopyButtons = true

   [params.homeInfoParams]
     Title = "你好，我是 XXX 👋"
     Content = "这里是我的个人主页，我会在这里记录技术、项目和生活。"

   [[params.socialIcons]]
     name = "github"
     url = "https://github.com/jupro2"

   [[menu.main]]
     identifier = "posts"
     name = "文章"
     url = "/posts/"
     weight = 10

   [[menu.main]]
     identifier = "about"
     name = "关于"
     url = "/about/"
     weight = 20